import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

const appRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const repoRoot = resolve(appRoot, '../..')
const assets = join(appRoot, 'assets')
const source = join(assets, 'icon-master.png')
const linuxIcons = join(assets, 'icons')
const themeAssets = join(repoRoot, 'packages/client/ui-codepilot-theme/assets')
const themeBrandCss = join(repoRoot, 'packages/client/ui-codepilot-theme/src/client/brand-icon.module.css')
const masterSize = 1024
// ChatGPT, VS Code, and other installed macOS app icons keep their visible
// artwork near 83–84% of the legacy ICNS canvas. The transparent inset keeps
// Pilot Harness at the same optical size in Dock, Finder, and app switcher.
const platformArtworkSize = 856
const platformInset = (masterSize - platformArtworkSize) / 2
const cornerRadius = Math.round(224 * platformArtworkSize / masterSize)

mkdirSync(linuxIcons, { recursive: true })
mkdirSync(themeAssets, { recursive: true })

const mask = Buffer.from(`
  <svg width="${platformArtworkSize}" height="${platformArtworkSize}" viewBox="0 0 ${platformArtworkSize} ${platformArtworkSize}">
    <rect width="${platformArtworkSize}" height="${platformArtworkSize}" rx="${cornerRadius}" fill="#fff"/>
  </svg>
`)
const roundedArtwork = await sharp(source)
  .resize(platformArtworkSize, platformArtworkSize, { fit: 'cover' })
  .composite([{ input: mask, blend: 'dest-in' }])
  .png()
  .toBuffer()
const platformMaster = await sharp({
  create: {
    width: masterSize,
    height: masterSize,
    channels: 4,
    background: { r: 0, g: 0, b: 0, alpha: 0 },
  },
})
  .composite([{ input: roundedArtwork, left: platformInset, top: platformInset }])
  .png()
  .toBuffer()

async function pngAt(size) {
  return sharp(platformMaster).resize(size, size).png().toBuffer()
}

writeFileSync(join(assets, 'icon.png'), await pngAt(512))
writeFileSync(join(assets, 'brand-icon.png'), await sharp(roundedArtwork).resize(256, 256).png().toBuffer())

// The CodePilot theme is an unloadable browser plugin, so its product mark is
// embedded into plugin-owned CSS instead of depending on a desktop-only URL.
const themeBrandIcon = await sharp(roundedArtwork).resize(128, 128).png().toBuffer()
writeFileSync(join(themeAssets, 'pilot-harness-icon.png'), themeBrandIcon)
writeFileSync(themeBrandCss, `/* Generated by apps/desktop/scripts/generate-icons.mjs. */
html[data-codepilot-theme] {
  --pilot-brand-icon: url('data:image/png;base64,${themeBrandIcon.toString('base64')}');
}
`)

const linuxSizes = [16, 32, 48, 64, 128, 256, 512, 1024]
for (const size of linuxSizes) {
  writeFileSync(join(linuxIcons, `${size}x${size}.png`), await pngAt(size))
}

const icoSizes = [16, 24, 32, 48, 64, 128, 256]
const icoImages = await Promise.all(icoSizes.map(pngAt))
const directorySize = 6 + icoImages.length * 16
const directory = Buffer.alloc(directorySize)
directory.writeUInt16LE(0, 0)
directory.writeUInt16LE(1, 2)
directory.writeUInt16LE(icoImages.length, 4)

let imageOffset = directorySize
for (let index = 0; index < icoImages.length; index++) {
  const size = icoSizes[index]
  const image = icoImages[index]
  const entry = 6 + index * 16
  directory.writeUInt8(size === 256 ? 0 : size, entry)
  directory.writeUInt8(size === 256 ? 0 : size, entry + 1)
  directory.writeUInt8(0, entry + 2)
  directory.writeUInt8(0, entry + 3)
  directory.writeUInt16LE(1, entry + 4)
  directory.writeUInt16LE(32, entry + 6)
  directory.writeUInt32LE(image.length, entry + 8)
  directory.writeUInt32LE(imageOffset, entry + 12)
  imageOffset += image.length
}
writeFileSync(join(assets, 'icon.ico'), Buffer.concat([directory, ...icoImages]))

const icnsSizes = [
  ['icp4', 16],
  ['icp5', 32],
  ['icp6', 64],
  ['ic07', 128],
  ['ic08', 256],
  ['ic09', 512],
  ['ic10', 1024],
]
const icnsImages = await Promise.all(icnsSizes.map(([, size]) => pngAt(size)))
const icnsChunks = icnsImages.map((image, index) => {
  const chunkHeader = Buffer.alloc(8)
  chunkHeader.write(icnsSizes[index][0], 0, 4, 'ascii')
  chunkHeader.writeUInt32BE(image.length + 8, 4)
  return Buffer.concat([chunkHeader, image])
})
const icnsHeader = Buffer.alloc(8)
icnsHeader.write('icns', 0, 4, 'ascii')
icnsHeader.writeUInt32BE(8 + icnsChunks.reduce((total, chunk) => total + chunk.length, 0), 4)
writeFileSync(join(assets, 'icon.icns'), Buffer.concat([icnsHeader, ...icnsChunks]))

const ico = readFileSync(join(assets, 'icon.ico'))
console.log(`Generated Pilot Harness platform and in-app icons (${ico.length} byte ICO) from assets/icon-master.png`)
